Flowershop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('booking/', include('booking.urls')),

]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

booking/urls.py
from . import views
from django.urls import path

app_name='booking'
urlpatterns = [
    path('',views.booking,name='booking'),
    path('conformed/',views.conform,name='conform')


]

members/urls.py
from django.urls import path
from .views import UserRegisterView


urlpatterns = [
    path('register/',UserRegisterView.as_view(),name='register'),


]

shop/urls.py
from . import views
from django.urls import path

app_name='shop'
urlpatterns = [
    path('',views.demo,name='demo'),




]

booking/models.py
from django.db import models


# Create your models here.
class Branch(models.Model):
    Bname=models.CharField(max_length=250)
    SubBranch1=models.CharField(max_length=250)
    SubBranch2=models.CharField(max_length=250)

    def __str__(self):
        return self.Bname


class book(models.Model):
    name=models.CharField(max_length=250)
    adress=models.CharField(max_length=250)
    Email=models.EmailField()
    phone=models.IntegerField()
    category=models.ForeignKey(Branch,on_delete=models.CASCADE)
    flower=models.ForeignKey('shop.Flower',on_delete=models.CASCADE)
    Quantity=models.IntegerField()

    def __str__(self):
        return self.name

members/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

# Create your models here.
class Flower(models.Model):
    name=models.CharField(max_length=250)
    price=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

booking/views.py
from django.shortcuts import render, redirect
from . models import book,Branch
from shop.models import Flower
#Create your views here.

def booking(request):
        flower = Flower.objects.all()
        branch=Branch.objects.all()
        if request.method == 'POST':
            name = request.POST.get('name', )
            address = request.POST.get('address', )
            phone = request.POST.get('phone', )
            flo = book(name=name,  phone=phone ,address=address,flower=flower,branch=branch)
            flo.save()
            return redirect('/')
        return render(request, 'booking.html',{'showflower':flower,'branch':branch})
def conform(request):
    return render(request,'conformed.html')
from django.shortcuts import render, redirect
from . models import book,Branch
from shop.models import Flower
#Create your views here.

def booking(request):
    print("tesy")
    flower = Flower.objects.all()
    branch=Branch.objects.all()
    if request.method == 'POST':
        print("post")
        name = request.POST.get('firstname', )
        flId= request.POST.get('flower', )
        email=request.POST.get('email',)
        flower1=Flower.objects.get(id=flId)
        address = request.POST.get('address', )
        branchId=request.POST.get('branch', )
        branchselected=Branch.objects.get(id=branchId)
        phone = request.POST.get('phone', )
        Quantity=request.POST.get('quantity')
        flo = book(name=name,Email=email,  phone=phone , Quantity=Quantity,adress=address,flower=flower1,category=branchselected)
        flo.save()
        return redirect('/booking/conformed')
    return render(request, 'booking.html',{'showflower':flower,'branch':branch})
def conform(request):
    return render(request,'conformed.html')

members/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


# Create your views here.
class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

# Create your views here.

shop/views.py
from . models import Flower
from django.shortcuts import render, redirect
# Create your views here.
#def demo(request):
    #return HttpResponse('hello world')
#@login_required
def demo(request):
    pass
    # flower=Flower.objects.all()
    # context={
    #     'flower_list':flower
    # }


    # return render(request,'main.html',context)
    return render(request,'main.html')

templates/booking.html
{% load static %}

{% block body %}
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>



    <style>
body{
  font-family: Calibri, Helvetica, sans-serif;
  background-color: pink;
}
.container {
    padding: 50px;
  background-color: lightblue;
}

input[type=text], input[type=number], textarea {
  width: 100%;
  padding: 5px;
  margin: 5px 0 10px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  background-color: orange;
  outline: none;
}
 div {
            padding: 10px 0;
         }
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}
</style>
</head>
<body>

<form method="post">
    {% csrf_token %}
  <div class="container">
  <center>  <h1> Booking</h1> </center>
  <hr>
  <label> Name </label>
<input type="text" name="firstname" placeholder= "name" size="10" required />
<label> Address: </label>
<input type="text" name="address" placeholder="address" size="15"required />

<label> Phone: </label>
<input type="text" name="phone" placeholder="phone" size="15"required />


 <label for="email"><b>Email</b></label>
 <input type="text" placeholder="Enter Email" name="email" required>

       <p><b>District : </b>
         <select name="district" class="form-control">
   {% for branch in branch %}
            <option value="{{ branch.id }}">{{ branch.Bname}}</option>
   {% endfor %}
         </select>
</p>

          <p><b>Branch : </b>
         <select name="branch" class="form-control">
   {% for branch in branch %}
            <option value="{{ branch.id}}">{{ branch.SubBranch1}}</option>
             <option value="{{ branch.id}}">{{ branch.SubBranch2}}</option>

   {% endfor %}
         </select>
</p>

       <p><b>Flower : </b>
         <select name="flower" class="form-control">
   {% for flower in showflower %}
            <option value="{{ flower.id}}">{{ flower.name}}-{{flower.price}}</option>
   {% endfor %}
         </select>
</p>

           Quantity:<input type="number" name="quantity" size="15" required /><br>

<!--           <a class="btn btn-secondary" href="{% url 'booking:conform' %}">Submit</a>-->
    <button type="submit" class="btn btn-warning"   >Book Now</button>
          <a class="btn btn-warning" href="{% url 'shop:demo' %}"  >Back </button>




<!--    <button type="submit" class="registerbtn" value="{% url 'booking:conform' %}"   >Book Now</button>-->
</form>

</html>
{% endblock %}

templates/conformed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h4>Your order conformed</h4>
           <a class="btn btn-secondary" href="{% url 'logout' %}">OK</a>

</body>
</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/header.html
{% load static %}
<!--<header>
    <center>
        <img src="{% static 'img/logo.png' %}"alt="logoimage">
    </center>
</header>-->

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="description" content="{% block metadescription %}{% endblock %}">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link rel="stylesheet" href="{% static 'style.css' %}">


    <title>{% block title %}{% endblock %}</title>


</head>

<body>
<!--<body id="bg" style="background-image:url('{% static 'img/bg.jpg' %}'); background-repeat:no-repeat;background-size:auto;background-attachment: fixed;">-->
<!-- Home -->

<!--	<div class="home">-->
<!--		<div class="background_image" style="background-image:url({% static 'img/bg.jpg' %})"></div>-->
<!--	</div>-->

<div class="container">

{% include 'header.html' %}
{% include 'navbar.html' %}
<div class="card">
    <img src="{% static 'img/bg.jpg' %}" alt="fwl" class="mx-auto d-block img-fluid card-img-top">
    <div class="card-img-overlay">
        <h1 class="card-title text-dark mt-1">fresh flower</h1>
                {% block content %}

        <a href="{% url 'login' %}" class="btn btn-dark text-white">shop now</a>
        {% endblock %}

    </div>
</div>
    {% for i in flower_list %}
    <img src="{{i.img.url}}" width="100" height="100">
        {{i.name}}----->{{i.price}}
    {% endfor %}
<!--<div class=" text-center">-->
<!--<div class="col-md-6">-->
<!--        <a class="btn btn-danger" href="{% url 'login' %}">shop here..</a>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->



{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>



</body>
</html>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Flower Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Booking-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <li><a class="dropdown-item" href="{% url 'booking:booking' %}">Malappuram</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Kozhikkode</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Alappuzha</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Trivandram</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Eranakkulam</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Kannur</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Kottayam</a></li>-->


<!--          </ul>-->
<!--        </li>-->

<!--      </ul>-->


      <!--<form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>
</body>
</html>
{% endblock %}